POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "braulio",
    "lastname": "chavez",
    "secondLastname": "andrade",
    "age": 23,
    "email": "brauliochaveza@gmail.com",
    "password": "123456",
    "cp": "13400",
    "state": "CDMX",
    "area": "tlahuac",
    "profession": "developer"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/auth/recover-password
Content-Type: application/json      

{
    "email": "brauliochaveza@gmail.com"
}

###
POST http://localhost:5000/auth/reset-password
Content-Type: application/json      

{
    "email": "brauliochaveza@gmail.com",
    "password": "123",
    "passwordResetCode": "[}@=r3o9Oa"
}

###
POST http://localhost:5000/report/
Content-Type: application/json

{
    "title": "Reporte de prueba",
    "description": "Este es un reporte de prueba",
    "location": "CDMX",
    "longitude": -99.1332,
    "latitude": 19.4326,
    "userId": "44bc9b63-49e7-4423-896a-d8553278b56b"
}